import type { Metadata } from 'next'
import '@styles/globals.scss'
// import '@styles/breakpoints.scss'
import Navbar from '@components/Navbar'
import Topbar from '@components/Topbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="layout">
          <Navbar />
          <Topbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
